apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../../kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: boots
  name: boots
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: boots
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ../../kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: boots
    spec:
      containers:
        - args:
            - -log-level
            - DEBUG
          env:
            - name: BOOTP_BIND
              value: 0.0.0.0:67
            - name: DATA_MODEL_VERSION
              value: "1"
            - name: DNS_SERVERS
              value: 8.8.8.8
            - name: DOCKER_REGISTRY
              value: 192.168.56.4
            - name: FACILITY_CODE
              value: onprem
            - name: HTTP_BIND
              value: 192.168.56.4:80
            - name: MIRROR_BASE_URL
              value: http://192.168.56.4:8080
            - name: PUBLIC_IP
              value: 192.168.56.4
            - name: REGISTRY_PASSWORD
              value: Admin1234
            - name: REGISTRY_USERNAME
              value: admin
            - name: SYSLOG_BIND
              value: 192.168.56.4:514
            - name: TFTP_BIND
              value: 192.168.56.4:69
            - name: TINKERBELL_GRPC_AUTHORITY
              value: 192.168.56.4:42113
            - name: TINKERBELL_TLS
              value: ' false'
          image: quay.io/tinkerbell/boots:sha-505785d7
          name: boots
          resources: {}
      restartPolicy: Always
status: {}
